listener:
  addr: :80

log:
  level: warn
  # we are using sentry for error collection,
  # you could opt-out by disabling it on the following line
  disable_sentry: false

sentry:
  dsn: https://989409410d0740a89b1f8571c4195dca@sentry.tokend.services/3

horizon:
  endpoint: http://janus
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4

janus:
  endpoint: http://janus:8000
  upstream: http://charts
  surname:  charts
