log:
  level: warn
  # we are using sentry for error collection,
  # you could opt-out by disabling it on the following line
  disable_sentry: false

sentry:
  dsn: https://1bbe444efb3b4b15a58d9c0aba739f1c@sentry.tokend.services/6

horizon:
  endpoint: http://janus
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4

listener:
  addr: :80

janus:
  disabled: true
  endpoint: http://janus:8000
  upstream: http://coinpayments_atomic_swap
  surname:  coinpayments_atomic_swap

coinpayments:
  merchant_id: "6936542314febfcc8dd3955fce88e0be"
  address: https://www.coinpayments.net/api.php
  private_key: "1004f66dB4081cA6D9c3f0651A1DC64eB754158e48daFb7441c4B632D26628eC"
  public_key: "f1db0de9c54cac677109f9da823b9627bef1c606fa75634c776100b88170a271"
  ipn_secret: "supersekr1tandsecure"
  request_timeout: 30

atomic_swap:
  forbill_endpoint: http://janus
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4
  price_asset: UAH
