horizon:
  endpoint: "http://horizon"
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"

withdraw:
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  owner: "GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB"

rpc:
  endpoint: "http://63.32.188.217:8545"

transfer:
  seed: "75603080DAED3924A5544F6815688A2E94F07C89864BFB750D99A8F107B8E3E8"
  address: "0x9266798B4469275e844C94f747b4e35Dc6aD8D77"
  confirmations: 20

log:
  level: debug
  disable_sentry: true
