rpc:
  endpoint: "ws://63.32.188.217:8546"

ethereum:
  checkpoint: 6106200 #block to start listening for deposits from
  confirmations: 1 #number of confirmations to wait for

horizon:
  endpoint: "http://horizon"
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"

deposit:
  asset_issuer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  asset_owner: "GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB"
  admin_signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"

funnel:
  gas_price: "30"
  threshold: "50"
  hot_wallet: "0x9266798B4469275e844C94f747b4e35Dc6aD8D77"
  private_key: "75603080DAED3924A5544F6815688A2E94F07C89864BFB750D99A8F107B8E3E8"

deployer:
  private_key: "75603080DAED3924A5544F6815688A2E94F07C89864BFB750D99A8F107B8E3E8"
  gas_price: "30"
  gas_limit: "400000"
  contract_owner: "0x9266798B4469275e844C94f747b4e35Dc6aD8D77"
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  contract_count: 5

log:
  level: debug
  disable_sentry: true