rpc:
  endpoint: "ws://63.32.188.217:8546"

ethereum:
  checkpoint: 8882144 #block to start listening for deposits from
  confirmations: 1 #number of confirmations to wait for

token_url:
  disabled: false

horizon:
  endpoint: "http://horizon"
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"

deposit:
  admin_signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  etherscan_url: "https://ropsten.etherscan.io/"

funnel:
  gas_price: "20"
  threshold: "0"
  hot_wallet: "0x9266798B4469275e844C94f747b4e35Dc6aD8D77"
  private_key: "75603080DAED3924A5544F6815688A2E94F07C89864BFB750D99A8F107B8E3E8"

deployer:
  private_key: "75603080DAED3924A5544F6815688A2E94F07C89864BFB750D99A8F107B8E3E8"
  gas_price: "20"
  gas_limit: "300000"
  contract_owner: "0x9266798B4469275e844C94f747b4e35Dc6aD8D77"
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  contract_count: 5

nft_svc:
  endpoint: "http://nft-svc"

log:
  level: debug
  disable_sentry: true

