log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://marketplace:marketplace@marketplace_db/marketplace?sslmode=disable"

horizon:
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4
  endpoint: "http://traefik/"

listener:
  addr: :80

marketplace:
  payment_signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  skip_sign_check: false
  tx_expiration_time: 30m

cop:
  endpoint: http://cop
  upstream: http://marketplace
  service_name: "marketplace-service"
  service_port: "80"
  service_prefix: "/integrations/marketplace"

coinpayments:
  merchant_id: "6936542314febfcc8dd3955fce88e0be"
  address: https://www.coinpayments.net/api.php
  private_key: "1004f66dB4081cA6D9c3f0651A1DC64eB754158e48daFb7441c4B632D26628eC"
  public_key: "f1db0de9c54cac677109f9da823b9627bef1c606fa75634c776100b88170a271"
  ipn_secret: "supersekr1tandsecure"
  request_timeout: 30

4bill:
  url: https://api.4bill.io
  api_key: 'M~xcKKT"Wi7{~oCruo"L,j_|[I._zA.W'
  point: "339"
  debug: true

payer:
  private_payer: false
  payment_service_id: 2
  dl_account_id: 317
  dl_wallet_id: 476
  payments_asset: "UAH"
  fixed_fee: 500 # kopiyky
  dynamic_fee: 0.0125 # %
  debug: true

nft_svc:
  endpoint: http://nft-svc