log:
  level: warn
  # we are using sentry for error collection,
  # you could opt-out by disabling it on the following line
  disable_sentry: true

sentry:
  dsn: https://1bbe444efb3b4b15a58d9c0aba739f1c@sentry.tokend.services/6

closer:
  source: GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB
  signer: SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4
  concurrency: 100

horizon:
  endpoint: http://traefik/
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"

listener:
  addr: :2324
