closer:
  source: "GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB"
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"
  normal_time: 1m
  abnormal_period: 1m
  max_abnormal_period: 5m

listener:
  addr: :2323

horizon:
  endpoint: http://traefik/
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"

log:
  level: warn
  # we are using sentry for error collection,
  # you could opt-out by disabling it on the following line
  disable_sentry: false

sentry:
  dsn: https://3168b86d1fe34f1b95247afc100fa7ad@sentry.tokend.services/8
